name: task05
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

#Packages
  cupertino_icons: ^1.0.6
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
#  freezed: ^2.5.2
  geolocator: ^11.0.0
  geocoding: ^3.0.0
#  freezed_annotation: ^2.4.1
  url_launcher: ^6.2.6
  permission_handler:
  location: ^6.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
